version: 2

models:
  - name: stg_stock_prices_unified
    description: Unified and cleaned stock prices from historical and streaming sources
    config:
      tags: ['staging', 'silver']
    columns:
      - name: symbol
        description: Stock ticker symbol
        tests:
          - not_null
      - name: trade_date
        description: Trading date
        tests:
          - not_null
      - name: trade_datetime
        description: Trading date and time
        tests:
          - not_null
      - name: open_price
        description: Opening price
      - name: high_price
        description: Highest price
      - name: low_price
        description: Lowest price
      - name: close_price
        description: Closing price
      - name: volume
        description: Trading volume (parsed from string notation)
      - name: change_pct
        description: Percentage change from previous close
      - name: data_source
        description: Source of the data (HISTORICAL or STREAMING)
        tests:
          - accepted_values:
              values: ['HISTORICAL', 'STREAMING']
      - name: is_complete
        description: Flag indicating all OHLCV fields are present
      - name: has_anomaly
        description: Flag indicating data quality issues
      - name: processed_at
        description: Timestamp when record was processed by dbt
