version: 2

sources:
  - name: bronze
    description: Raw data loaded from S3 (historical CSV + streaming JSON)
    database: EGX_OPERATIONAL_DB
    schema: BRONZE
    tables:
      - name: bronze_stock_prices_historical
        description: Historical stock prices from S3 CSV files (2019-2023)
        columns:
          - name: symbol
            description: Stock ticker symbol (may have nulls - filtered in Silver)
          - name: date_str
            description: Date string in MM/DD/YYYY format
          - name: price
            description: Closing price
          - name: open
            description: Opening price
          - name: high
            description: Highest price
          - name: low
            description: Lowest price
          - name: volume_str
            description: Volume string with K/M notation (e.g., "2.55M")
          - name: change_pct
            description: Daily percentage change
            
      - name: bronze_stock_prices_streaming
        description: Real-time stock prices from S3 JSON files (streaming data)
        columns:
          - name: symbol
            description: Stock ticker symbol
            tests:
              - not_null
          - name: datetime
            description: Timestamp of the price data
            tests:
              - not_null
          - name: open
            description: Opening price
          - name: high
            description: Highest price
          - name: low
            description: Lowest price
          - name: close
            description: Closing price
          - name: volume
            description: Trading volume
